// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHr5810KP-7dAj2LzhcWjQx4gX_6sk9i8',
    appId: '1:603554239643:web:ea9aa943aa9e8baab4e23e',
    messagingSenderId: '603554239643',
    projectId: 'flutter-chat-app-1304b',
    authDomain: 'flutter-chat-app-1304b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1304b.appspot.com',
    measurementId: 'G-R53PQW8RVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8JxvlY5WT8p_1r5d_6atts-6sEsldjHg',
    appId: '1:603554239643:android:09d3f20e5a17e0c9b4e23e',
    messagingSenderId: '603554239643',
    projectId: 'flutter-chat-app-1304b',
    storageBucket: 'flutter-chat-app-1304b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPx8vyaiCmjWJxw9cWxBAmP25R2Xkhr0c',
    appId: '1:603554239643:ios:43bf76494c86778ab4e23e',
    messagingSenderId: '603554239643',
    projectId: 'flutter-chat-app-1304b',
    storageBucket: 'flutter-chat-app-1304b.appspot.com',
    iosClientId: '603554239643-og1gior7ten4nf39f551sksegi97d6ut.apps.googleusercontent.com',
    iosBundleId: 'com.kkjang.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPx8vyaiCmjWJxw9cWxBAmP25R2Xkhr0c',
    appId: '1:603554239643:ios:43bf76494c86778ab4e23e',
    messagingSenderId: '603554239643',
    projectId: 'flutter-chat-app-1304b',
    storageBucket: 'flutter-chat-app-1304b.appspot.com',
    iosClientId: '603554239643-og1gior7ten4nf39f551sksegi97d6ut.apps.googleusercontent.com',
    iosBundleId: 'com.kkjang.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHr5810KP-7dAj2LzhcWjQx4gX_6sk9i8',
    appId: '1:603554239643:web:f07621d26a1b02d2b4e23e',
    messagingSenderId: '603554239643',
    projectId: 'flutter-chat-app-1304b',
    authDomain: 'flutter-chat-app-1304b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1304b.appspot.com',
    measurementId: 'G-PLFCE4R0LQ',
  );

}